# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = app
TARGET = QtUI
DESTDIR = ../x64/Release
CONFIG += release
LIBS += -L"."
DEPENDPATH += .
MOC_DIR += .
OBJECTS_DIR += release
UI_DIR += .
RCC_DIR += .
win32:RC_FILE = QtUI.rc
HEADERS += ./resource.h \
    ./DialogUI.h \
    ./SystemTray.h
SOURCES += ./SystemTray.cpp \
    ./DialogUI.cpp \
    ./main.cpp
RESOURCES += QtUI.qrc
